import type { Lang } from "@/lib/i18n/translations";

/**
 * Testi delle pagine del sito multipagina: IT, EN, DE, FR.
 * Tono informativo ed elegante: descrivere, non spingere.
 * Ogni pagina ha una sola call to action di prenotazione (campo `cta`).
 */
export const content = {
  it: {
    common: {
      book: "Prenota",
      photoSoon: "Fotografia in arrivo",
      discover: "Scopri",
      allRooms: "Tutte le camere",
      backToRooms: "Torna alle camere",
      otherRooms: "Le altre camere",
      room: "Camera",
      skip: "Vai al contenuto",
      menu: "Menu",
      language: "Lingua",
      address: "Montopoli in Sabina (RI), Lazio — Italia",
      rights: "Tutti i diritti riservati.",
    },
    home: {
      metaTitle: "Orbis in Sabina | Casa vacanze a Montopoli in Sabina",
      metaDescription:
        "Casa vacanze a Montopoli in Sabina con cinque camere dedicate ai continenti, sauna, palestra, vasca idromassaggio e terrazzo panoramico con vista sulla Cupola di San Pietro.",
      eyebrow: "Casa vacanze · Montopoli in Sabina",
      title: "Orbis in Sabina",
      lead: "Cinque camere dedicate ai cinque continenti, un'area benessere riservata agli ospiti e un terrazzo affacciato sulle colline della Sabina, a meno di un'ora da Roma.",
      introEyebrow: "Il mondo in una casa",
      introTitle: "Un nome, un'idea",
      introText: [
        "Orbis, in latino, significa mondo. È l'idea da cui nasce la casa: accogliere sotto lo stesso tetto il carattere di cinque continenti, ciascuno interpretato in una camera attraverso colori, materiali e dettagli.",
        "Intorno, il paesaggio è quello della Sabina: uliveti, borghi in pietra e un orizzonte che nelle giornate limpide arriva fino a Roma.",
      ],
      roomsEyebrow: "Cinque camere",
      roomsTitle: "Un continente per ogni camera",
      houseEyebrow: "Spazi comuni",
      houseTitle: "Il benessere, dentro casa",
      houseText:
        "Sauna, palestra, vasca idromassaggio e un terrazzo panoramico sono a disposizione degli ospiti durante tutto il soggiorno.",
      houseLink: "Scopri la casa",
      territoryEyebrow: "Il territorio",
      territoryTitle: "La Sabina, a un passo da Roma",
      territoryText:
        "Montopoli in Sabina è un borgo collinare in provincia di Rieti, tra l'Abbazia di Farfa, la valle del Tevere e la Via Salaria. Roma è a circa quarantacinque minuti.",
      territoryLink: "Esplora il territorio",
      cta: {
        title: "Il vostro soggiorno in Sabina",
        text: "Consultate le date disponibili e scegliete il canale di prenotazione che preferite.",
        button: "Verifica la disponibilità",
      },
    },
    rooms: {
      metaTitle: "Camere",
      metaDescription:
        "Le cinque camere di Orbis in Sabina, ciascuna dedicata a un continente: Europa, Asia, Africa, Americhe e Oceania.",
      eyebrow: "Cinque continenti, una sola casa",
      title: "Le camere",
      lead: "Ogni camera racconta un continente attraverso colori, materiali e dettagli, con lo stesso livello di cura e di comfort.",
      cta: {
        title: "Avete scelto la vostra camera?",
        text: "Il calendario delle disponibilità è aggiornato in tempo reale dalle piattaforme di prenotazione.",
        button: "Verifica la disponibilità",
      },
    },
    room: {
      amenities: "Dotazioni",
      gallery: "Galleria",
      ctaTitle: (name: string) => `Soggiornare nella camera ${name}`,
      ctaText: "Consultate le date libere e prenotate direttamente dalla pagina contatti.",
      ctaButton: (name: string) => `Prenota la camera ${name}`,
    },
    house: {
      metaTitle: "La Casa",
      metaDescription:
        "Gli spazi di Orbis in Sabina: sauna, palestra, vasca idromassaggio e terrazzo panoramico con binocolo puntato sulla Cupola di San Pietro.",
      eyebrow: "La casa",
      title: "Spazi pensati per rallentare",
      lead: "Oltre alle cinque camere, la casa offre agli ospiti un'area benessere completa e un terrazzo da cui, nelle giornate limpide, si vede Roma.",
      conceptTitle: "Una casa, cinque viaggi",
      conceptText: [
        "Orbis in Sabina è una casa vacanze di fascia alta con cinque camere, ciascuna intitolata e arredata secondo un continente. Gli spazi comuni sono condivisi tra gli ospiti e pensati per offrire, dentro casa, ciò che di solito si cerca fuori.",
        "Ogni ambiente è curato per accompagnare giornate lente: il calore della sauna, l'allenamento del mattino, l'acqua dell'idromassaggio al tramonto.",
      ],
      spacesEyebrow: "Benessere e spazi comuni",
      spacesTitle: "Cosa trovate in casa",
      galleryEyebrow: "Galleria",
      galleryTitle: "Uno sguardo alla casa",
      cta: {
        title: "Una pausa in Sabina",
        text: "Gli spazi comuni sono inclusi nel soggiorno per tutti gli ospiti.",
        button: "Verifica la disponibilità",
      },
    },
    territory: {
      metaTitle: "Territorio",
      metaDescription:
        "Montopoli in Sabina e dintorni: l'Abbazia di Farfa, la Riserva Naturale Tevere-Farfa, i borghi sabini e Roma a circa 45 minuti.",
      eyebrow: "Il territorio",
      title: "La Sabina, tra colline e storia",
      lead: "Montopoli in Sabina si trova in provincia di Rieti, sulle colline tra la valle del Tevere e la Via Salaria: la quiete della campagna a meno di un'ora dal centro di Roma.",
      distancesTitle: "Distanze indicative",
      distances: [
        { place: "Roma centro", time: "circa 45 minuti in auto" },
        { place: "Aeroporto di Fiumicino", time: "circa 55 minuti in auto" },
        { place: "Abbazia di Farfa", time: "pochi minuti in auto" },
      ],
      placesEyebrow: "Nei dintorni",
      placesTitle: "Luoghi da visitare",
      places: [
        {
          name: "Borgo di Montopoli in Sabina",
          photo: "/foto/borgo-vicolo.webp",
          text: "Il centro storico in pietra, con vicoli, scorci panoramici sulla valle e la tranquillità dei borghi collinari sabini.",
        },
        {
          name: "Abbazia di Farfa",
          text: "Una delle abbazie benedettine più importanti d'Italia, con il borgo che la circonda e le sue botteghe artigiane.",
        },
        {
          name: "Riserva Naturale Tevere-Farfa",
          text: "Un'area protetta lungo il Tevere, tra zone umide e sentieri, apprezzata per le passeggiate e l'osservazione degli uccelli.",
        },
        {
          name: "Roma",
          photo: "/foto/vista-cupola-san-pietro.webp",
          text: "Raggiungibile in giornata. E dal terrazzo della casa, con il binocolo, si scorge la Cupola di San Pietro.",
        },
      ],
      mapTitle: "Dove siamo",
      cta: {
        title: "Una base tranquilla per scoprire la Sabina",
        text: "Verificate le date disponibili per il vostro soggiorno.",
        button: "Verifica la disponibilità",
      },
    },
    contact: {
      metaTitle: "Contatti e prenotazioni",
      metaDescription:
        "Contatti, disponibilità e prenotazione di Orbis in Sabina, casa vacanze a Montopoli in Sabina (Rieti).",
      eyebrow: "Contatti",
      title: "Contatti e prenotazioni",
      lead: "Per informazioni sul soggiorno potete scriverci in qualsiasi momento. Qui sotto trovate il calendario delle disponibilità e il link per prenotare.",
      infoTitle: "Recapiti",
      addressLabel: "Indirizzo",
      emailLabel: "Email",
      whatsappLabel: "WhatsApp",
      whatsappText: "Scriveteci su WhatsApp",
      socialLabel: "Social",
      bookingEyebrow: "Prenota",
      bookingTitle: "Disponibilità",
      bookingText: "Il calendario mostra le date già occupate. Le date libere si possono prenotare direttamente online.",
      bookButton: "Prenota il soggiorno",
      bookFallback: "Richiedi disponibilità su WhatsApp",
      alsoAirbnb: "La casa è disponibile anche su Airbnb",
      mapTitle: "Come arrivare",
    },
  },
  en: {
    common: {
      book: "Book",
      photoSoon: "Photograph coming soon",
      discover: "Discover",
      allRooms: "All rooms",
      backToRooms: "Back to rooms",
      otherRooms: "The other rooms",
      room: "Room",
      skip: "Skip to content",
      menu: "Menu",
      language: "Language",
      address: "Montopoli in Sabina (RI), Lazio — Italy",
      rights: "All rights reserved.",
    },
    home: {
      metaTitle: "Orbis in Sabina | Holiday home in Montopoli in Sabina",
      metaDescription:
        "Holiday home in Montopoli in Sabina with five continent-themed rooms, sauna, gym, hot tub and a panoramic terrace overlooking St. Peter's Dome.",
      eyebrow: "Holiday home · Montopoli in Sabina",
      title: "Orbis in Sabina",
      lead: "Five rooms dedicated to the five continents, a private wellness area for guests and a terrace overlooking the Sabine hills, less than an hour from Rome.",
      introEyebrow: "The world in one house",
      introTitle: "A name, an idea",
      introText: [
        "Orbis is Latin for world. It is the idea behind the house: to bring the character of five continents under one roof, each one interpreted in a room through colours, materials and details.",
        "All around lies the Sabine countryside: olive groves, stone villages and a horizon that, on clear days, reaches all the way to Rome.",
      ],
      roomsEyebrow: "Five rooms",
      roomsTitle: "A continent for every room",
      houseEyebrow: "Shared spaces",
      houseTitle: "Wellness, inside the house",
      houseText:
        "A sauna, a gym, a hot tub and a panoramic terrace are available to guests throughout their stay.",
      houseLink: "Discover the house",
      territoryEyebrow: "Surroundings",
      territoryTitle: "Sabina, a step from Rome",
      territoryText:
        "Montopoli in Sabina is a hilltop village in the province of Rieti, between Farfa Abbey, the Tiber valley and the ancient Via Salaria. Rome is about forty-five minutes away.",
      territoryLink: "Explore the area",
      cta: {
        title: "Your stay in Sabina",
        text: "Check the available dates and choose the booking channel you prefer.",
        button: "Check availability",
      },
    },
    rooms: {
      metaTitle: "Rooms",
      metaDescription:
        "The five rooms of Orbis in Sabina, each dedicated to a continent: Europe, Asia, Africa, the Americas and Oceania.",
      eyebrow: "Five continents, one house",
      title: "The rooms",
      lead: "Each room tells the story of a continent through colours, materials and details, with the same level of care and comfort.",
      cta: {
        title: "Found your room?",
        text: "The availability calendar is updated in real time from our booking platforms.",
        button: "Check availability",
      },
    },
    room: {
      amenities: "Amenities",
      gallery: "Gallery",
      ctaTitle: (name: string) => `Staying in the ${name} room`,
      ctaText: "Check the free dates and book directly from the contact page.",
      ctaButton: (name: string) => `Book the ${name} room`,
    },
    house: {
      metaTitle: "The House",
      metaDescription:
        "The spaces of Orbis in Sabina: sauna, gym, hot tub and a panoramic terrace with binoculars pointed at St. Peter's Dome.",
      eyebrow: "The house",
      title: "Spaces designed to slow down",
      lead: "Beyond the five rooms, the house offers guests a complete wellness area and a terrace from which, on clear days, you can see Rome.",
      conceptTitle: "One house, five journeys",
      conceptText: [
        "Orbis in Sabina is an upscale holiday home with five rooms, each named and furnished after a continent. The shared spaces are open to all guests and designed to offer, inside the house, what one usually looks for elsewhere.",
        "Every space is arranged for slow days: the warmth of the sauna, a morning workout, the hot tub at sunset.",
      ],
      spacesEyebrow: "Wellness and shared spaces",
      spacesTitle: "What you'll find in the house",
      galleryEyebrow: "Gallery",
      galleryTitle: "A look inside the house",
      cta: {
        title: "A break in Sabina",
        text: "The shared spaces are included in the stay for all guests.",
        button: "Check availability",
      },
    },
    territory: {
      metaTitle: "Surroundings",
      metaDescription:
        "Montopoli in Sabina and its surroundings: Farfa Abbey, the Tevere-Farfa Nature Reserve, Sabine villages and Rome about 45 minutes away.",
      eyebrow: "Surroundings",
      title: "Sabina, between hills and history",
      lead: "Montopoli in Sabina lies in the province of Rieti, on the hills between the Tiber valley and the Via Salaria: countryside calm less than an hour from central Rome.",
      distancesTitle: "Approximate distances",
      distances: [
        { place: "Central Rome", time: "about 45 minutes by car" },
        { place: "Fiumicino Airport", time: "about 55 minutes by car" },
        { place: "Farfa Abbey", time: "a few minutes by car" },
      ],
      placesEyebrow: "Nearby",
      placesTitle: "Places to visit",
      places: [
        {
          name: "Montopoli in Sabina",
          photo: "/foto/borgo-vicolo.webp",
          text: "The stone-built historic centre, with narrow lanes, views over the valley and the quiet of the Sabine hill villages.",
        },
        {
          name: "Farfa Abbey",
          text: "One of the most important Benedictine abbeys in Italy, with the small village and craft workshops around it.",
        },
        {
          name: "Tevere-Farfa Nature Reserve",
          text: "A protected area along the Tiber, with wetlands and trails, popular for walks and birdwatching.",
        },
        {
          name: "Rome",
          photo: "/foto/vista-cupola-san-pietro.webp",
          text: "Easily reached for a day trip. And from the house terrace, through the binoculars, you can spot St. Peter's Dome.",
        },
      ],
      mapTitle: "Where we are",
      cta: {
        title: "A quiet base to discover Sabina",
        text: "Check the available dates for your stay.",
        button: "Check availability",
      },
    },
    contact: {
      metaTitle: "Contact and booking",
      metaDescription:
        "Contact details, availability and booking for Orbis in Sabina, holiday home in Montopoli in Sabina (Rieti).",
      eyebrow: "Contact",
      title: "Contact and booking",
      lead: "For any information about your stay, feel free to write to us at any time. Below you will find the availability calendar and the booking link.",
      infoTitle: "Details",
      addressLabel: "Address",
      emailLabel: "Email",
      whatsappLabel: "WhatsApp",
      whatsappText: "Message us on WhatsApp",
      socialLabel: "Social",
      bookingEyebrow: "Book",
      bookingTitle: "Availability",
      bookingText: "The calendar shows the dates already booked. Free dates can be booked directly online.",
      bookButton: "Book your stay",
      bookFallback: "Ask for availability on WhatsApp",
      alsoAirbnb: "The house is also listed on Airbnb",
      mapTitle: "Getting here",
    },
  },
  de: {
    common: {
      book: "Buchen",
      photoSoon: "Foto folgt in Kürze",
      discover: "Entdecken",
      allRooms: "Alle Zimmer",
      backToRooms: "Zurück zu den Zimmern",
      otherRooms: "Die anderen Zimmer",
      room: "Zimmer",
      skip: "Zum Inhalt springen",
      menu: "Menü",
      language: "Sprache",
      address: "Montopoli in Sabina (RI), Latium — Italien",
      rights: "Alle Rechte vorbehalten.",
    },
    home: {
      metaTitle: "Orbis in Sabina | Ferienhaus in Montopoli in Sabina",
      metaDescription:
        "Ferienhaus in Montopoli in Sabina mit fünf Zimmern im Zeichen der Kontinente, Sauna, Fitnessraum, Whirlpool und Panoramaterrasse mit Blick auf die Kuppel des Petersdoms.",
      eyebrow: "Ferienhaus · Montopoli in Sabina",
      title: "Orbis in Sabina",
      lead: "Fünf Zimmer, den fünf Kontinenten gewidmet, ein privater Wellnessbereich für die Gäste und eine Terrasse mit Blick auf die Hügel der Sabina – weniger als eine Stunde von Rom.",
      introEyebrow: "Die Welt in einem Haus",
      introTitle: "Ein Name, eine Idee",
      introText: [
        "Orbis bedeutet auf Latein Welt. Das ist die Idee hinter dem Haus: den Charakter von fünf Kontinenten unter einem Dach zu vereinen – jeder davon in einem Zimmer durch Farben, Materialien und Details interpretiert.",
        "Ringsum liegt die Landschaft der Sabina: Olivenhaine, Dörfer aus Stein und ein Horizont, der an klaren Tagen bis nach Rom reicht.",
      ],
      roomsEyebrow: "Fünf Zimmer",
      roomsTitle: "Ein Kontinent für jedes Zimmer",
      houseEyebrow: "Gemeinschaftsbereiche",
      houseTitle: "Wellness im eigenen Haus",
      houseText:
        "Sauna, Fitnessraum, Whirlpool und eine Panoramaterrasse stehen den Gästen während des gesamten Aufenthalts zur Verfügung.",
      houseLink: "Das Haus entdecken",
      territoryEyebrow: "Die Umgebung",
      territoryTitle: "Die Sabina, nur einen Schritt von Rom",
      territoryText:
        "Montopoli in Sabina ist ein Hügeldorf in der Provinz Rieti, zwischen der Abtei Farfa, dem Tibertal und der antiken Via Salaria. Rom ist etwa fünfundvierzig Minuten entfernt.",
      territoryLink: "Die Umgebung erkunden",
      cta: {
        title: "Ihr Aufenthalt in der Sabina",
        text: "Sehen Sie sich die freien Termine an und wählen Sie den Buchungskanal, den Sie bevorzugen.",
        button: "Verfügbarkeit prüfen",
      },
    },
    rooms: {
      metaTitle: "Zimmer",
      metaDescription:
        "Die fünf Zimmer von Orbis in Sabina, jedes einem Kontinent gewidmet: Europa, Asien, Afrika, Amerika und Ozeanien.",
      eyebrow: "Fünf Kontinente, ein Haus",
      title: "Die Zimmer",
      lead: "Jedes Zimmer erzählt von einem Kontinent – durch Farben, Materialien und Details, mit derselben Sorgfalt und demselben Komfort.",
      cta: {
        title: "Ihr Zimmer gefunden?",
        text: "Der Verfügbarkeitskalender wird in Echtzeit von den Buchungsplattformen aktualisiert.",
        button: "Verfügbarkeit prüfen",
      },
    },
    room: {
      amenities: "Ausstattung",
      gallery: "Galerie",
      ctaTitle: (name: string) => `Übernachten im Zimmer ${name}`,
      ctaText: "Sehen Sie sich die freien Termine an und buchen Sie direkt über die Kontaktseite.",
      ctaButton: (name: string) => `Zimmer ${name} buchen`,
    },
    house: {
      metaTitle: "Das Haus",
      metaDescription:
        "Die Räume von Orbis in Sabina: Sauna, Fitnessraum, Whirlpool und eine Panoramaterrasse mit Fernglas, das auf die Kuppel des Petersdoms gerichtet ist.",
      eyebrow: "Das Haus",
      title: "Räume zum Entschleunigen",
      lead: "Neben den fünf Zimmern bietet das Haus einen kompletten Wellnessbereich und eine Terrasse, von der aus man an klaren Tagen Rom sieht.",
      conceptTitle: "Ein Haus, fünf Reisen",
      conceptText: [
        "Orbis in Sabina ist ein gehobenes Ferienhaus mit fünf Zimmern, jedes nach einem Kontinent benannt und eingerichtet. Die Gemeinschaftsbereiche teilen sich die Gäste; sie sollen im Haus bieten, was man sonst draußen sucht.",
        "Jeder Raum ist für ruhige Tage gestaltet: die Wärme der Sauna, das Training am Morgen, der Whirlpool bei Sonnenuntergang.",
      ],
      spacesEyebrow: "Wellness und Gemeinschaftsbereiche",
      spacesTitle: "Was Sie im Haus erwartet",
      galleryEyebrow: "Galerie",
      galleryTitle: "Ein Blick ins Haus",
      cta: {
        title: "Eine Auszeit in der Sabina",
        text: "Die Gemeinschaftsbereiche sind für alle Gäste im Aufenthalt inbegriffen.",
        button: "Verfügbarkeit prüfen",
      },
    },
    territory: {
      metaTitle: "Umgebung",
      metaDescription:
        "Montopoli in Sabina und Umgebung: die Abtei Farfa, das Naturschutzgebiet Tevere-Farfa, die Dörfer der Sabina und Rom in etwa 45 Minuten.",
      eyebrow: "Die Umgebung",
      title: "Die Sabina, zwischen Hügeln und Geschichte",
      lead: "Montopoli in Sabina liegt in der Provinz Rieti, auf den Hügeln zwischen dem Tibertal und der Via Salaria: ländliche Ruhe, weniger als eine Stunde vom Zentrum Roms.",
      distancesTitle: "Ungefähre Entfernungen",
      distances: [
        { place: "Zentrum von Rom", time: "ca. 45 Minuten mit dem Auto" },
        { place: "Flughafen Fiumicino", time: "ca. 55 Minuten mit dem Auto" },
        { place: "Abtei Farfa", time: "wenige Minuten mit dem Auto" },
      ],
      placesEyebrow: "In der Umgebung",
      placesTitle: "Sehenswerte Orte",
      places: [
        {
          name: "Montopoli in Sabina",
          photo: "/foto/borgo-vicolo.webp",
          text: "Der historische Ortskern aus Stein, mit engen Gassen, Ausblicken ins Tal und der Ruhe der Hügeldörfer der Sabina.",
        },
        {
          name: "Abtei Farfa",
          text: "Eine der bedeutendsten Benediktinerabteien Italiens, mit dem kleinen Dorf und den Handwerksläden ringsum.",
        },
        {
          name: "Naturschutzgebiet Tevere-Farfa",
          text: "Ein Schutzgebiet am Tiber mit Feuchtgebieten und Wanderwegen, beliebt für Spaziergänge und Vogelbeobachtung.",
        },
        {
          name: "Rom",
          photo: "/foto/vista-cupola-san-pietro.webp",
          text: "Bequem als Tagesausflug erreichbar. Und von der Terrasse des Hauses sieht man mit dem Fernglas die Kuppel des Petersdoms.",
        },
      ],
      mapTitle: "Hier finden Sie uns",
      cta: {
        title: "Ein ruhiger Ausgangspunkt, um die Sabina zu entdecken",
        text: "Prüfen Sie die freien Termine für Ihren Aufenthalt.",
        button: "Verfügbarkeit prüfen",
      },
    },
    contact: {
      metaTitle: "Kontakt und Buchung",
      metaDescription:
        "Kontakt, Verfügbarkeit und Buchung für Orbis in Sabina, Ferienhaus in Montopoli in Sabina (Rieti).",
      eyebrow: "Kontakt",
      title: "Kontakt und Buchung",
      lead: "Für Fragen zu Ihrem Aufenthalt können Sie uns jederzeit schreiben. Unten finden Sie den Verfügbarkeitskalender und den Buchungslink.",
      infoTitle: "Kontaktdaten",
      addressLabel: "Adresse",
      emailLabel: "E-Mail",
      whatsappLabel: "WhatsApp",
      whatsappText: "Schreiben Sie uns auf WhatsApp",
      socialLabel: "Social Media",
      bookingEyebrow: "Buchen",
      bookingTitle: "Verfügbarkeit",
      bookingText: "Der Kalender zeigt die bereits belegten Tage. Freie Termine können direkt online gebucht werden.",
      bookButton: "Aufenthalt buchen",
      bookFallback: "Verfügbarkeit per WhatsApp anfragen",
      alsoAirbnb: "Das Haus ist auch auf Airbnb verfügbar",
      mapTitle: "Anreise",
    },
  },
  fr: {
    common: {
      book: "Réserver",
      photoSoon: "Photo bientôt disponible",
      discover: "Découvrir",
      allRooms: "Toutes les chambres",
      backToRooms: "Retour aux chambres",
      otherRooms: "Les autres chambres",
      room: "Chambre",
      skip: "Aller au contenu",
      menu: "Menu",
      language: "Langue",
      address: "Montopoli in Sabina (RI), Latium — Italie",
      rights: "Tous droits réservés.",
    },
    home: {
      metaTitle: "Orbis in Sabina | Maison de vacances à Montopoli in Sabina",
      metaDescription:
        "Maison de vacances à Montopoli in Sabina avec cinq chambres dédiées aux continents, sauna, salle de sport, jacuzzi et terrasse panoramique avec vue sur la coupole de Saint-Pierre.",
      eyebrow: "Maison de vacances · Montopoli in Sabina",
      title: "Orbis in Sabina",
      lead: "Cinq chambres dédiées aux cinq continents, un espace bien-être réservé aux hôtes et une terrasse face aux collines de la Sabine, à moins d'une heure de Rome.",
      introEyebrow: "Le monde dans une maison",
      introTitle: "Un nom, une idée",
      introText: [
        "Orbis signifie monde en latin. C'est l'idée d'où naît la maison : réunir sous un même toit le caractère de cinq continents, chacun interprété dans une chambre à travers couleurs, matières et détails.",
        "Tout autour s'étend la campagne de la Sabine : oliveraies, villages de pierre et un horizon qui, par temps clair, s'étend jusqu'à Rome.",
      ],
      roomsEyebrow: "Cinq chambres",
      roomsTitle: "Un continent pour chaque chambre",
      houseEyebrow: "Espaces communs",
      houseTitle: "Le bien-être, à la maison",
      houseText:
        "Sauna, salle de sport, jacuzzi et terrasse panoramique sont à la disposition des hôtes pendant tout le séjour.",
      houseLink: "Découvrir la maison",
      territoryEyebrow: "La région",
      territoryTitle: "La Sabine, à deux pas de Rome",
      territoryText:
        "Montopoli in Sabina est un village perché de la province de Rieti, entre l'abbaye de Farfa, la vallée du Tibre et l'antique Via Salaria. Rome est à environ quarante-cinq minutes.",
      territoryLink: "Explorer la région",
      cta: {
        title: "Votre séjour en Sabine",
        text: "Consultez les dates disponibles et choisissez le canal de réservation que vous préférez.",
        button: "Voir les disponibilités",
      },
    },
    rooms: {
      metaTitle: "Chambres",
      metaDescription:
        "Les cinq chambres d'Orbis in Sabina, chacune dédiée à un continent : Europe, Asie, Afrique, Amériques et Océanie.",
      eyebrow: "Cinq continents, une seule maison",
      title: "Les chambres",
      lead: "Chaque chambre raconte un continent à travers couleurs, matières et détails, avec le même soin et le même confort.",
      cta: {
        title: "Vous avez choisi votre chambre ?",
        text: "Le calendrier des disponibilités est mis à jour en temps réel depuis les plateformes de réservation.",
        button: "Voir les disponibilités",
      },
    },
    room: {
      amenities: "Équipements",
      gallery: "Galerie",
      ctaTitle: (name: string) => `Séjourner dans la chambre ${name}`,
      ctaText: "Consultez les dates libres et réservez directement depuis la page contact.",
      ctaButton: (name: string) => `Réserver la chambre ${name}`,
    },
    house: {
      metaTitle: "La Maison",
      metaDescription:
        "Les espaces d'Orbis in Sabina : sauna, salle de sport, jacuzzi et terrasse panoramique avec des jumelles tournées vers la coupole de Saint-Pierre.",
      eyebrow: "La maison",
      title: "Des espaces pensés pour ralentir",
      lead: "En plus des cinq chambres, la maison offre aux hôtes un espace bien-être complet et une terrasse d'où, par temps clair, on aperçoit Rome.",
      conceptTitle: "Une maison, cinq voyages",
      conceptText: [
        "Orbis in Sabina est une maison de vacances haut de gamme de cinq chambres, chacune nommée et aménagée d'après un continent. Les espaces communs sont partagés entre les hôtes et pensés pour offrir, à la maison, ce que l'on cherche habituellement ailleurs.",
        "Chaque espace accompagne des journées paisibles : la chaleur du sauna, l'entraînement du matin, le jacuzzi au coucher du soleil.",
      ],
      spacesEyebrow: "Bien-être et espaces communs",
      spacesTitle: "Ce que vous trouverez dans la maison",
      galleryEyebrow: "Galerie",
      galleryTitle: "Un aperçu de la maison",
      cta: {
        title: "Une pause en Sabine",
        text: "Les espaces communs sont inclus dans le séjour pour tous les hôtes.",
        button: "Voir les disponibilités",
      },
    },
    territory: {
      metaTitle: "Alentours",
      metaDescription:
        "Montopoli in Sabina et ses alentours : l'abbaye de Farfa, la réserve naturelle Tevere-Farfa, les villages de la Sabine et Rome à environ 45 minutes.",
      eyebrow: "La région",
      title: "La Sabine, entre collines et histoire",
      lead: "Montopoli in Sabina se trouve dans la province de Rieti, sur les collines entre la vallée du Tibre et la Via Salaria : le calme de la campagne à moins d'une heure du centre de Rome.",
      distancesTitle: "Distances indicatives",
      distances: [
        { place: "Centre de Rome", time: "environ 45 minutes en voiture" },
        { place: "Aéroport de Fiumicino", time: "environ 55 minutes en voiture" },
        { place: "Abbaye de Farfa", time: "quelques minutes en voiture" },
      ],
      placesEyebrow: "Aux alentours",
      placesTitle: "Lieux à visiter",
      places: [
        {
          name: "Montopoli in Sabina",
          photo: "/foto/borgo-vicolo.webp",
          text: "Le centre historique en pierre, avec ses ruelles, ses vues sur la vallée et le calme des villages perchés de la Sabine.",
        },
        {
          name: "Abbaye de Farfa",
          text: "L'une des plus importantes abbayes bénédictines d'Italie, entourée de son petit village et de ses boutiques d'artisans.",
        },
        {
          name: "Réserve naturelle Tevere-Farfa",
          text: "Une zone protégée le long du Tibre, entre zones humides et sentiers, appréciée pour les promenades et l'observation des oiseaux.",
        },
        {
          name: "Rome",
          photo: "/foto/vista-cupola-san-pietro.webp",
          text: "Facile à rejoindre pour la journée. Et depuis la terrasse de la maison, avec les jumelles, on aperçoit la coupole de Saint-Pierre.",
        },
      ],
      mapTitle: "Où nous trouver",
      cta: {
        title: "Un point de départ paisible pour découvrir la Sabine",
        text: "Vérifiez les dates disponibles pour votre séjour.",
        button: "Voir les disponibilités",
      },
    },
    contact: {
      metaTitle: "Contact et réservation",
      metaDescription:
        "Coordonnées, disponibilités et réservation d'Orbis in Sabina, maison de vacances à Montopoli in Sabina (Rieti).",
      eyebrow: "Contact",
      title: "Contact et réservation",
      lead: "Pour toute information sur votre séjour, écrivez-nous à tout moment. Vous trouverez ci-dessous le calendrier des disponibilités et le lien de réservation.",
      infoTitle: "Coordonnées",
      addressLabel: "Adresse",
      emailLabel: "E-mail",
      whatsappLabel: "WhatsApp",
      whatsappText: "Écrivez-nous sur WhatsApp",
      socialLabel: "Réseaux sociaux",
      bookingEyebrow: "Réserver",
      bookingTitle: "Disponibilités",
      bookingText: "Le calendrier indique les dates déjà réservées. Les dates libres peuvent être réservées directement en ligne.",
      bookButton: "Réserver votre séjour",
      bookFallback: "Demander les disponibilités sur WhatsApp",
      alsoAirbnb: "La maison est aussi disponible sur Airbnb",
      mapTitle: "Comment venir",
    },
  },
} satisfies Record<Lang, unknown>;

export type SiteContent = (typeof content)["it"];
